import Link from "next/link";
import "./globals.css";
import LinkButton from "./client_component";

export const metadata = {
  title: "next.js 복습",
  description: "Generated by 이정민",
};

export default async function RootLayout({ children }) {
  const posts = await fetch(process.env.NEXT_PUBLIC_POST_URL, {cache:'no-cache'});
  const list = await posts.json();
  return (
    <html>
      <body>
        <h2><a href="/">Back to Main</a></h2>
        <LinkButton/>
        {children}
        <div>
          <ul>
            <p><b>글 리스트</b></p>
            {list.map(post => {
              return <li className="post-list" key={post.id}><Link href={`/read/${post.id}`}>{post.title}</Link></li>
            })}
          </ul>
        </div>
      </body>
    </html>
  );
}